// <auto-generated />
using KiemTraMvc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KiemTraMvc.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250724084034_BangLop")]
    partial class BangLop
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("KiemTraMvc.Models.Hieu", b =>
                {
                    b.Property<int>("HieuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sđt")
                        .HasColumnType("INTEGER");

                    b.HasKey("HieuId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KiemTraMvc.Models.Lop", b =>
                {
                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sđt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tuoi")
                        .HasColumnType("INTEGER");

                    b.HasKey("FullName");

                    b.ToTable("Lop");
                });
#pragma warning restore 612, 618
        }
    }
}
